---
# Dev settings
:api_key: 2698f594c7091997d0b52f1e1b9e9f86
:password: 75361c2a051bb27ff41f3f275da93c44
:store: up-dog-toys-2.myshopify.com
:theme_id: 83629830
# Live settings
# :api_key: 4eada98331c7eee600a6b5c01b17e44c
# :password: 19619a910f5e4843b6b30e28f52fe99c
# :store: up-dog-toys.myshopify.com
# :theme_id: 65864325  # copy
:ignore_files:
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
